from datetime import datetime
from typing import Optional
from pydantic import BaseModel

import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

from simulator.signals.enums import Signal

class StrategyDecision(BaseModel):
    """
    Structured output generated by a strategy during the runtime execution.
    """
    signal: Signal
    timestamp: datetime
    symbol: str
    reasoning: Optional[str] = None
    strategy_name: str
